---
name: Docker Build basic

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build-image:
    name: Building Image
    runs-on: ubuntu-22.04

    steps:
      - name: Logining to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Building Image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ggshe4ka/httpenv-basic:latest, ggshe4ka/httpenv-basic:0.1 